### ISSUE TITLE
Project Model wizard does not create "new item" entry

### ISSUE THREAD

**Issue by kgaylord** [AugerArchitecture/P2P#19] opened 2015-09-07 14:31 UTC
In "Thumbnail Plan" mode while using the SoftCo/ServiceCo/Joint Offering model

```
When adding an item to the Project Model the wizard comes up and you can fill it in but when you go to "Add Item" the new item does not appear in the Project Model
```

**Comment by karlonauger** [comment] 2015-09-08 15:45
Duplicate of #20

**Closed as completed** 2015-09-08 15:45 UTC
Labels: duplicate
